### PR TITLE
Update Matomo Java Tracker to 3.0.3

### PR DESCRIPTION
**Pull request by dheid**
Second pull request. See here: https://github.com/identifiers-org/cloud-satellite-web-spa/pull/32

### CODE REVIEW

**Comment by dheid** [comment]
Ping

**Comment by renatocjn** [comment]
Not sure if this is automated PR or not, but just in case it isn't. We are updating the several microservices, we will review this when it's time to update the resolver.

**Comment by dheid** [comment]
No, not automated. 😆

**Comment by renatocjn** [comment]
Thank you @dheid

**Pull request merged**
